server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:ms-loan-application}
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false

logging:
  level:
    root: "INFO"
    co.com.pragma: "DEBUG"
    org.springframework.r2dbc: "WARN"
    io.r2dbc.postgresql.QUERY: "INFO"
    io.r2dbc.postgresql.PARAM: "WARN"

adapters:
  r2dbc:
    host: ${ADAPTERS_R2DBC_HOST:localhost}
    port: ${ADAPTERS_R2DBC_PORT:5432}
    database: ${ADAPTERS_R2DBC_DATABASE:crediya_loan_db}
    schema: ${ADAPTERS_R2DBC_SCHEMA:public}
    username: ${ADAPTERS_R2DBC_USERNAME:crediya}
    password: ${ADAPTERS_R2DBC_PASSWORD:crediya2025}
  profiles:
    include: ${ADAPTERS_PROFILES_INCLUDE:}

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:"http://localhost:4200,http://localhost:8080"}
routes:
  paths:
    loans: "/api/v1/solicitud"
    actuator: "/actuator/health"

adapter:
  restconsumer:
    timeout: ${ADAPTER_RESTCONSUMER_TIMEOUT:3000}
    url: ${ADAPTER_RESTCONSUMER_URL:"http://ms-authentication:8080"}

resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"

jwt:
  secret: ${JWT_SECRET:GKU2sCyjHN2D4KXdLKsxRn3UDKI1TjTdP3pxzMzfIE8=}
  expiration: ${JWT_EXPIRATION:3600}
  jws-algorithms: HS256